### ISSUE TITLE
Is there a way to pass alloyeditor native configuration ?

### ISSUE THREAD

**Issue by irongomme** [thiagogarbazza/angular-alloyeditor#1]
It could be great to pass configuration in alloyeditor tag parameter, is there a way to do that ?

**Comment by thiagogarbazza** [comment]
A release 0.0.4 version contains this tag parameter, see the solution bellow:

``` html
<alloy-editor id="myEditor" name="myEditor" ng-model="model.content" config="editor.config"></alloy-editor>
```
